# Generated by Django 4.2 on 2023-08-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
        ('app', '0003_service_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.main_category'),
        ),
    ]
